version: '3'
services:
  nginx:
    container_name: acme_nginx
    image: nginx:alpine
    env_file:
      - './.app.env'
    volumes:
      - './docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template'
      - './:/var/www/api'
    working_dir: '/var/www/api'
    environment:
      - NGINX_HOST=${NGINX_HOST}
    networks:
      - proxy
      - app
    ports:
      - ${WEB_IP}:${WEB_HTTP_PORT}:80
    command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always
    depends_on:
      - php
  php:
    container_name: acme_app
    image: php:7.2-fpm
    volumes:
      - './:/var/www/api'
    working_dir: '/var/www/api'
    environment:
      XDEBUG_CONFIG: "remote_host=${LOCAL_IP}"
    networks:
      - app
    restart: always
  composer:
    container_name: acme_composer
    image: "composer"
    volumes:
      - './:/var/www/api'
    working_dir: '/var/www/api'
    command: install
    depends_on:
      - php
networks:
  proxy:
    driver: bridge
  app:
    driver: bridge